networks:
  my_network:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://rirxre:M324Atlas@cluster0.1usp6em.mongodb.net/todoapp?retryWrites=true&w=majority&appName=Cluster0
      - FRONTEND_URL=http://localhost:5173
      - JWT_SECRET=dein_geheimes_passwort
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - my_network
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    command: ["npm", "run", "dev", "--", "--host"]

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped
    networks:
      - my_network
