name: Deploy to Render

on:
  push:
    branches:
      - main  # Ändere das, wenn du eine andere Branch verwendest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Backend to Render
        run: curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

      - name: Deploy Frontend to Render
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
